[package]
name = "dog_bite_analysis"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]
description = "A dog bite data analysis tool"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
chrono = "0.4"
